vk:
  # –í–∫–ª—é—á–µ–Ω–∞ –ª–∏ –ø—Ä–∏–≤—è–∑–∫–∞ –∫ –í–ö, –µ—Å–ª–∏ –≤—ã –æ—Ç–∫–ª—é—á–∏—Ç–µ –ø—Ä–∏–≤—è–∑–∫—É –∏–≥—Ä–æ–∫–∏ –Ω–µ —Å–º–æ–≥—É—Ç –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–∞—Ç—å –≤—Ö–æ–¥, –ø—Ä–∏–≤—è–∑—ã–≤–∞—Ç—å –∞–∫–∫–∞—É–Ω—Ç—ã.
  enabled: false
  
  # –Æ–∑–µ—Ä—ã –í–ö —É –∫–æ—Ç–æ—Ä—ã—Ö –±—É–¥–µ—Ç –∞–¥–º–∏–Ω –¥–æ—Å—Ç—É–ø –∫ –ø—Ä–∏–≤—è–∑–∞–Ω–Ω—ã–º –∞–∫–∫–∞—É–Ω—Ç–∞–º
  # –£ —é–∑–µ—Ä–æ–≤ —Å –∞–¥–º–∏–Ω-–¥–æ—Å—Ç—É–ø–æ–º –µ—Å—Ç—å –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏:
  # 1. –û—Ç–≤—è–∑—ã–≤–∞—Ç—å, –º–µ–Ω—è—Ç—å –Ω–∏–∫, –∫–∏–∫–∞—Ç—å –∏—Å–ø–æ–ª—å–∑—É—è –æ–±—ã—á–Ω—ã–µ –∫–æ–º–∞–Ω–¥—ã, –∏ –ø—Ä–∏ —ç—Ç–æ–º –Ω–µ –±—É–¥–µ—Ç –ø—Ä–æ–≤–µ—Ä–∫–∏ –Ω–∞ –≤–ª–∞–¥–µ–Ω–∏–µ –∞–∫–∫–∞—É–Ω—Ç–∞.
  # 2. –ü—Ä–∏ –≤–≤–æ–¥–µ /adminpanel –≤–∞–º –ø–æ–∫–∞–∂–µ—Ç –∞–¥–º–∏–Ω –ø–∞–Ω–µ–ª—å
  admin-accounts:
    - 123456789 #–°—é–¥–∞ –≤–∞—à id –≤–∫

  # –û–ø—Ä–µ–¥–µ–ª—è–µ—Ç –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–∏–≤—è–∑–æ–∫ –∫ –æ–¥–Ω–æ–º—É –∏ —Ç–æ–º—É –∂–µ vkId. –ü–æ—Å—Ç–∞–≤—å—Ç–µ 0 —á—Ç–æ–±—ã –æ—Ç–∫–ª—é—á–∏—Ç—å –ª–∏–º–∏—Ç
  max-vk-link: 0

  # –°–ø–æ—Å–æ–±—ã –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è –ø—Ä–∏–≤—è–∑–∫–∏ –∞–∫–∫–∞—É–Ω—Ç–∞ –∫ —Å–æ—Ü. —Å–µ—Ç–∏
  # FROM_GAME - –ò–≥—Ä–æ–∫ –æ—Ç–ø—Ä–∞–≤–ª—è–µ—Ç –∑–∞–ø—Ä–æ—Å —Å –ø–æ–º–æ—â—å—é –≤–≤–æ–¥–∞ –∫–æ–º–∞–Ω–¥—ã –≤ —Å–æ—Ü. —Å–µ—Ç–∏, –∏ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–∞–µ—Ç –ø—Ä–∏–≤—è–∑–∫—É –≤ –∏–≥—Ä–µ
  # FROM_LINK - –ò–≥—Ä–æ–∫ –æ—Ç–ø—Ä–∞–≤–ª—è–µ—Ç –∑–∞–ø—Ä–æ—Å —Å –ø–æ–º–æ—â—å—é –≤–≤–æ–¥–∞ –∫–æ–º–∞–Ω–¥—ã –≤ –∏–≥—Ä–µ, –∏ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–∞–µ—Ç –ø—Ä–∏–≤—è–∑–∫—É –≤ —Å–æ—Ü. —Å–µ—Ç–∏
  link-confirm-ways:
    - FROM_LINK

  confirmation:
    # –ó–∞ —Å–∫–æ–ª—å–∫–æ –≤—Ä–µ–º–µ–Ω–∏ –∏–≥—Ä–æ–∫ –¥–æ–ª–∂–µ–Ω –ø—Ä–∏–≤—è–∑–∞—Ç—å –∞–∫–∫–∞—É–Ω—Ç
    # –í—Ä–µ–º—è –º–æ–∂–Ω–æ —É–∫–∞–∑—ã–≤–∞—Ç—å –≤ –≤–∏–¥–µ:
    # y,–≥    - –≥–æ–¥           5y 5–≥
    # mo,–º–µ—Å - –º–µ—Å—è—Ü         5mo,5–º–µ—Å
    # w,–Ω    - –Ω–µ–¥–µ–ª—è        5w,5–Ω
    # d,–¥    - –¥–µ–Ω—å          5d 5–¥
    # h,—á    - —á–∞—Å           5h 5—á
    # m,–º    - –º–∏–Ω—É—Ç–∞        5m 5–º
    # s,—Å    - —Å–µ–∫—É–Ω–¥—ã       5—Å 5s
    # ms,–º—Å  - –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥—ã  5ms 5–º—Å
    # –ï—Å–ª–∏ –Ω–µ —É–∫–∞–∑—ã–≤–∞—Ç—å, —Ç–æ –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é —Å–µ–∫—É–Ω–¥—ã
    remove-delay: 120
    code-length: 6
    # –°–∏–º–≤–æ–ª—ã –∫–æ—Ç–æ—Ä—ã–µ –±—É–¥—É—Ç –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω—ã –≤ –∫–æ–¥–µ
    code-characters: '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    # –ú–æ–∂–µ—Ç –ª–∏ –∏–≥—Ä–æ–∫ –≤–∫–ª—é—á–∞—Ç—å/–≤—ã–∫–ª—é—á–∞—Ç—å –ø–æ–¥—Ç–≤–µ—Ä–¥–µ–Ω–∏–µ
    can-toggle: false

  enter:
    # –ó–∞ —Å–∫–æ–ª—å–∫–æ –≤—Ä–µ–º–µ–Ω–∏ –∏–≥—Ä–æ–∫ –¥–æ–ª–∂–µ–Ω –ø–æ–¥—Ç–≤–µ—Ä–¥–∏—Ç—å –≤—Ö–æ–¥ –≤ –∞–∫–∫–∞—É–Ω—Ç
    # –í—Ä–µ–º—è –º–æ–∂–Ω–æ —É–∫–∞–∑—ã–≤–∞—Ç—å –≤ –≤–∏–¥–µ:
    # y,–≥    - –≥–æ–¥           5y 5–≥
    # mo,–º–µ—Å - –º–µ—Å—è—Ü         5mo,5–º–µ—Å
    # w,–Ω    - –Ω–µ–¥–µ–ª—è        5w,5–Ω
    # d,–¥    - –¥–µ–Ω—å          5d 5–¥
    # h,—á    - —á–∞—Å           5h 5—á
    # m,–º    - –º–∏–Ω—É—Ç–∞        5m 5–º
    # s,—Å    - —Å–µ–∫—É–Ω–¥—ã       5—Å 5s
    # ms,–º—Å  - –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥—ã  5ms 5–º—Å
    # –ï—Å–ª–∏ –Ω–µ —É–∫–∞–∑—ã–≤–∞—Ç—å, —Ç–æ –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é —Å–µ–∫—É–Ω–¥—ã
    enter-delay: 60

  # –ù–∞—Å—Ç—Ä–æ–π–∫–∞ –∫–æ–¥–∞ –ø—Ä–∏ –≤–æ—Å—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω–∏–∏ –∞–∫–∫–∞—É–Ω—Ç–∞
  restore:
    code-length: 7 # –î–ª–∏–Ω–∞ –∫–æ–¥–∞
    # –°–∏–º–≤–æ–ª—ã –∫–æ—Ç–æ—Ä—ã–µ –±—É–¥—É—Ç –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω—ã –≤ –∫–æ–¥–µ
    code-characters: '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ'

  # –í—ã–∫–ª—é—á–∞–µ—Ç —Å–æ–æ–±—â–µ–Ω–∏—è –∏–∑ –±–µ—Å–µ–¥—ã
  disable-conversation-commands: true

  # –ö–æ–º–∞–Ω–¥—ã –∫–æ—Ç–æ—Ä—ã–µ –±—É–¥—É—Ç –≤ –∏–≥—Ä–µ, –∫ –ø—Ä–∏–º–µ—Ä—É /addvk, –∏–ª–∏ –∂–µ /code
  proxy-commands:
    link-game: # –£–∫–∞–∑—ã–≤–∞–π—Ç–µ –∫–æ–º–∞–Ω–¥—ã –ë–ï–ó –∑–Ω–∞–∫–∞ '/'
      main-command: 'addvk'

  # –ö–æ–º–∞–Ω–¥—ã –∫–æ—Ç–æ—Ä—ã–µ –≤ –í–ö
  vk-commands: # –û—Å–Ω–æ–≤–Ω—ã–µ –∫–æ–º–∞–Ω–¥—ã
    link-game:
      main-command: '/addvk'
    enter-accept: # Id –∫–æ–º–∞–Ω–¥—ã, –Ω–µ –º–µ–Ω—è—Ç—å!
      main-command: '/–ø—Ä–∏–Ω—è—Ç—å' # –û–±—è–∑–∞—Ç–µ–ª—å–Ω–æ–µ –ø–æ–ª–µ
      aliases: # –ù–µ –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ–µ –ø–æ–ª–µ, —ç—Ç–æ –∞–ª–∏–∞—Å—ã –∫ –∫–æ–º–∞–Ω–¥–µ
        - '/accept'
    enter-decline:
      main-command: '/–æ—Ç–∫–ª–æ–Ω–∏—Ç—å'
      aliases:
        - '/decline'
    change-pass:
      main-command: '/–ø–∞—Ä–æ–ª—å'
      aliases:
        - '/password'
    unlink:
      main-command: '/–æ—Ç–≤—è–∑–∞—Ç—å'
      aliases:
        - '/unlink'
    accounts:
      main-command: '/–∞–∫–∫–∞—É–Ω—Ç—ã'
      aliases:
        - '/accounts'
    account-control:
      main-command: '/–∫–æ–Ω—Ç—Ä–æ–ª—å'
      aliases:
        - '/control'
        - '/account-control'
        - '/–∞–∫–∫–∞—É–Ω—Ç-–∫–æ–Ω—Ç—Ä–æ–ª—å'
    kick:
      main-command: '/–∫–∏–∫'
      aliases:
        - '/kick'
    restore:
      main-command: '/–≤–æ—Å—Å—Ç–∞–Ω–æ–≤–∏—Ç—å'
      aliases:
        - '/restore'
    code:
      main-command: '/code'
    confirmation-toggle:
      main-command: '/–ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ'
      aliases:
        - '/entertoggle'
    google:
      main-command: '/–≥—É–≥–ª'
      aliases:
        - '/google'
    google-code:
      main-command: '/–≥—É–≥–ª–∫–æ–¥'
      aliases:
        - '/googlecode'
    google-remove:
      main-command: '/–≥—É–≥–ª–æ—Ç–≤—è–∑–∞—Ç—å'
      aliases:
        - '/googleunlink'
    admin-panel:
      main-command: '/–∞–¥–º–∏–Ω-–ø–∞–Ω–µ–ª—å' #/–∞–¥–º–∏–Ω-–ø–∞–Ω–µ–ª—å,/–∞–¥–º–∏–Ω–ø–∞–Ω–µ–ª—å,/–∞–¥–º–∏–Ω,/–ø–∞–Ω–µ–ª—å,/admin-panel,/adminpanel,/admin,/panel
      aliases: [ admin,/adminpanel,/admin,/panel,/admin-panel,/–ø–∞–Ω–µ–ª—å,/–∞–¥–º–∏–Ω,/–∞–¥–º–∏–Ω–ø–∞–Ω–µ–ª—å ]
  # –°–æ–∑–¥–∞–Ω–∏–µ –∫–æ–º–º–∞–Ω–¥ –≤ –≤–∫, –ø—Ä–∏–≥–æ–¥–∏—Ç—Å—è –¥–ª—è —Å–æ–∑–¥–∞–Ω–∏—è —Ç–∞–∫–∏—Ö –∫–æ–º–∞–Ω–¥ –∫–∞–∫: /–∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –∏ —Ç–∞–∫ –¥–∞–ª–µ–µ
  custom-commands:
    /–ø–æ–º–æ—â—å:
      answer: |
        /–ø—Ä–∏–Ω—è—Ç—å -> –ü–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ –≤—Ö–æ–¥–∞ —á–µ—Ä–µ–∑ –í–ö <br>
        /–æ—Ç–∫–ª–æ–Ω–∏—Ç—å -> –û—Ç–∫–ª–æ–Ω–µ–Ω–∏–µ –≤—Ö–æ–¥–∞ —á–µ—Ä–µ–∑ –í–ö <br>
        /–æ—Ç–≤—è–∑–∞—Ç—å [–Ω–∏–∫] -> –¥–ª—è –æ—Ç–≤—è–∑–∫–∏ –∞–∫–∫–∞—É–Ω—Ç–∞ <br>
        /–∞–∫–∫–∞—É–Ω—Ç—ã -> –ö–æ–Ω—Ç—Ä–æ–ª—å –∞–∫–∫–∞—É–Ω—Ç–æ–≤ —á–µ—Ä–µ–∑ –∫–Ω–æ–ø–∫–∏ (–ï—Å—Ç—å —Å–∏—Å—Ç–µ–º–∞ —Å—Ç—Ä–∞–Ω–∏—Ü –µ—Å–ª–∏ –±–æ–ª—å—à–µ 5 –∞–∫–∫–∞—É–Ω—Ç–æ–≤)<br>
        /–∫–∏–∫ [–Ω–∏–∫] -> –ö–∏–∫–Ω—É—Ç—å –∏–≥—Ä–æ–∫–∞ —Å —Å–µ—Ä–≤–µ—Ä–∞ <br>
        /–≤–æ—Å—Å—Ç–∞–Ω–æ–≤–∏—Ç—å [–Ω–∏–∫] -> –ö–∏–∫–∞–µ—Ç –∏–≥—Ä–æ–∫–∞ —Å —Å–µ—Ä–≤–µ—Ä–∞ –µ—Å–ª–∏ –æ–Ω –æ–Ω–ª–∞–π–Ω, —Å–±—Ä–∞—Å—ã–≤–∞–µ—Ç –ø–∞—Ä–æ–ª—å –Ω–∞ —Ä–∞–Ω–¥–æ–º–Ω—ã–π, –∏ —Å–±—Ä–∞—Å—ã–≤–∞–µ—Ç —Å–µ—Å—Å–∏—é <br>
        /–ø–∞—Ä–æ–ª—å [–Ω–∏–∫] [–Ω–æ–≤—ã–π –ø–∞—Ä–æ–ª—å] -> –ú–µ–Ω—è–µ—Ç –ø–∞—Ä–æ–ª—å –∞–∫–∫–∞—É–Ω—Ç–∞ <br>
        /–≥—É–≥–ª [–Ω–∏–∫] -> –ì–µ–Ω–µ—Ä–∏—Ä—É–µ—Ç –≥—É–≥–ª-–∫–æ–¥ –∏ QR-–ö–æ–¥ <br>
        /–≥—É–≥–ª–∫–æ–¥ [–Ω–∏–∫] [–∫–æ–¥] -> –ò—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –ø—Ä–∏ –≤—Ö–æ–¥–µ —Å –≥—É–≥–ª-–∞—É—Ç–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏–µ–π <br>
        /–≥—É–≥–ª–æ—Ç–≤—è–∑–∞—Ç—å [–Ω–∏–∫] -> –û—Ç–≤—è–∑—ã–≤–∞–µ—Ç –≥—É–≥–ª-–∞—É—Ç–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏—é <br>
        /–∫–æ–¥ (/code) -> –î–ª—è –ø—Ä–∏–≤—è–∑–∫–∏ –º–∞–π–Ω–∫—Ä–∞—Ñ—Ç –∞–∫–∫–∞—É–Ω—Ç–∞ –∫ –í–ö <br>
        /–∞–¥–º–∏–Ω-–ø–∞–Ω–µ–ª—å,/–∞–¥–º–∏–Ω–ø–∞–Ω–µ–ª—å,/–∞–¥–º–∏–Ω,/–ø–∞–Ω–µ–ª—å,/admin-panel,/adminpanel,/admin,/panel -> –ú–æ–∂–Ω–æ –∫–æ–Ω—Ç—Ä–æ–ª–∏—Ä–æ–≤–∞—Ç—å –ø—Ä–∏–≤—è–∑–∞–Ω–Ω—ã–µ, –Ω–µ –ø—Ä–∏–≤—è–∑–∞–Ω–Ω—ã–µ –∞–∫–∫–∞—É–Ω—Ç—ã
    command:
      #–ï—Å–ª–∏ –∏–≥—Ä–æ–∫ –≤–≤–µ–ª –Ω–µ–∏–∑–≤–µ—Å—Ç–Ω—É—é –∫–æ–º–∞–Ω–¥—É —Ç–æ –µ–º—É –Ω–∞–ø–∏—à–µ—Ç —Ç–æ —á—Ç–æ –∫–æ–º–∞–Ω–¥–∞ –Ω–µ –Ω–∞–π–¥–µ–Ω–∞
      regex: '^/(?!.*(–ø–æ–º–æ—â—å|–ø—Ä–∏–Ω—è—Ç—å|accept|–æ—Ç–∫–ª–æ–Ω–∏—Ç—å|decline|–æ—Ç–≤—è–∑–∞—Ç—å|unlink|–∞–∫–∫–∞—É–Ω—Ç—ã|accounts|–∫–æ–Ω—Ç—Ä–æ–ª—å|control|account-control|–∞–∫–∫–∞—É–Ω—Ç-–∫–æ–Ω—Ç—Ä–æ–ª—å|–∫–∏–∫|kick|–≤–æ—Å—Å—Ç–∞–Ω–æ–≤–∏—Ç—å|restore|–ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ|entertoggle|–≥—É–≥–ª|google|–≥—É–≥–ª–∫–æ–¥|googlecode|–≥—É–≥–ª–æ—Ç–≤—è–∑–∞—Ç—å|googleunlink|–ø–∞—Ä–æ–ª—å|password|–∫–æ–¥|code|–∞–¥–º–∏–Ω-–ø–∞–Ω–µ–ª—å|–∞–¥–º–∏–Ω–ø–∞–Ω–µ–ª—å|–∞–¥–º–∏–Ω|–ø–∞–Ω–µ–ª—å|admin-panel|adminpanel|admin|panel)).*$'
      answer: '–ö–æ–º–∞–Ω–¥–∞ –Ω–µ –Ω–∞–π–¥–µ–Ω–∞! –î–æ—Å—Ç—É–ø–Ω—ã–µ –∫–æ–º–∞–Ω–¥—ã: /–ø–æ–º–æ—â—å'
      button-ignore: true
  keyboards: # –î–ª—è —Å–æ–∑–¥–∞–Ω–∏—è JSON –∫–ª–∞–≤–∏–∞—Ç—É—Ä —Å–æ–≤–µ—Ç—É—é –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å https://severecloud.github.io/vk-keyboard/. –£—á—Ç—ã–≤–∞–π—Ç–µ —á—Ç–æ –ø–æ–ª–µ–∑–Ω–∞—è –Ω–∞–≥—Ä—É–∑–∫–∞ –¥–æ–ª–∂–Ω–∞ –∏–º–µ—Ç—å –ø–ª–µ–π—Å—Ö–æ–ª–¥–µ—Ä—ã
    # –ö–ª–∞–≤–∏–∞—Ç—É—Ä–∞ –≤ –≤–∏–¥–µ JSON
    confirmation: '{"buttons":[[{"action":{"type":"callback","label":"–ü—Ä–∏–Ω—è—Ç—å","payload":"\"/–ø—Ä–∏–Ω—è—Ç—å %name%\""},"color":"positive"},{"action":{"type":"callback","label":"–û—Ç–∫–ª–æ–Ω–∏—Ç—å","payload":"\"/–æ—Ç–∫–ª–æ–Ω–∏—Ç—å %name%\""},"color":"negative"}]],"inline":true}'
    accounts: >  # %account_{index}% - player name, %account_{index}_color% - color that represents is player offline or online
      {                    
      "buttons": [
        [
          {
            "action": {
              "type": "callback",
              "label": "%account_1%",
              "payload": "\"/control %account_1%\""
            },
            "color": "%account_1_color%"
          }
        ],
        [
          {
            "action": {
              "type": "callback",
              "label": "%account_2%",
              "payload": "\"/control %account_2%\""
            },
            "color": "%account_2_color%"
          }
        ],
        [
          {
            "action": {
              "type": "callback",
              "label": "%account_3%",
              "payload": "\"/control %account_3%\""
            },
            "color": "%account_3_color%"
          }
        ],
        [
          {
            "action": {
              "type": "callback",
              "label": "%account_4%",
              "payload": "\"/control %account_4%\""
            },
            "color": "%account_4_color%"
          }
        ],
        [
          {
            "action": {
              "type": "callback",
              "label": "%account_5%",
              "payload": "\"/control %account_5%\""
            },
            "color": "%account_5_color%"
          }
        ],
        [
          {
            "action": {
              "type": "callback",
              "label": "<-",
              "payload": "\"/accounts -page %previous_page% -pageSize %pageSize% -type %type%\""
            },
            "color": "primary"
          },
          {
            "action": {
              "type": "callback",
              "label": "->",
              "payload": "\"/accounts -page %next_page% -pageSize %pageSize% -type %type%\""
            },
            "color": "primary"
          }
        ]
      ],
      "inline": true
      }
    account: >
      {
        "buttons": [
          [
            {
              "action": {
                "type": "callback",
                "label": "–í–æ—Å—Å—Ç–∞–Ω–æ–≤–∏—Ç—å",
                "payload": "\"/restore %account_name%\""
              },
              "color": "primary"
            },
            {
              "action": {
                "type": "callback",
                "label": "–ö–∏–∫–Ω—É—Ç—å",
                "payload": "\"/kick %account_name%\""
              },
              "color": "primary"
            },
            {
              "action": {
                "type": "callback",
                "label": "–û—Ç–≤—è–∑–∞—Ç—å",
                "payload": "\"/unlink %account_name%\""
              },
              "color": "primary"
            }
          ]
        ],
        "inline": true
      }
    admin-panel: >
      {
        "buttons": [
          [
            {
              "action": {
                "type": "callback",
                "label": "–í—Å–µ –∞–∫–∫–∞—É–Ω—Ç—ã",
                "payload": "\"/accounts -type all\""
              },
              "color": "primary"
            },
            {
              "action": {
                "type": "callback",
                "label": "–í—Å–µ –ø—Ä–∏–≤—è–∑–∞–Ω–Ω—ã–µ –∞–∫–∫–∞—É–Ω—Ç—ã",
                "payload": "\"/accounts -type linked\""
              },
              "color": "primary"
            }
          ],
          [
            {
              "action": {
                "type": "callback",
                "label": "–ú–æ–∏ –∞–∫–∫–∞—É–Ω—Ç—ã",
                "payload": "\"/accounts\""
              },
              "color": "primary"
            }
          ]
        ],
        "inline": true
      }
  vk-messages: #–î–ª—è –ø–µ—Ä–µ–Ω–æ—Å–∞ —Å—Ç—Ä–æ–∫ –∏—Å–ø–æ–ª—å–∑—É–π—Ç–µ "<br>" –±–µ–∑ –∫–∞–≤—ã—á–µ–∫.
    account-not-found: '–ê–∫–∫–∞—É–Ω—Ç —Å —Ç–∞–∫–∏–º –Ω–µ –Ω–∞–π–¥–µ–Ω!'
    # –ü—Ä–∏–≤—è–∑–∫–∞ –í–ö
    confirmation-success: '–í—ã —É—Å–ø–µ—à–Ω–æ –ø—Ä–∏–≤—è–∑–∞–ª–∏ –∞–∫–∫–∞—É–Ω—Ç –∫ –í–ö'
    already-linked: '–ê–∫–∫–∞—É–Ω—Ç —É–∂–µ –ø—Ä–∏–≤—è–∑–∞–Ω –∫ –¥—Ä—É–≥–æ–º—É –í–ö!'
    confirmation-sent: '–í—Å—ë –ø–æ—á—Ç–∏ –≥–æ—Ç–æ–≤–æ. –ü–æ–¥—Ç–≤–µ—Ä–¥–∏ –ø—Ä–∏–≤—è–∑–∫—É –≤ –∏–≥—Ä–µ —á–µ—Ä–µ–∑ –∫–æ–º–∞–Ω–¥—É: /code %code%'
    confirmation-timed-out: '–í–Ω–∏–º–∞–Ω–∏–µ! –í—Ä–µ–º—è –∫–æ–¥–∞ –∏—Å—Ç–µ–∫–ª–æ. –°–≥–µ–Ω–µ—Ä–∏—Ä—É–π—Ç–µ –µ–≥–æ –∑–∞–Ω–æ–≥–æ'
    confirmation-no-code: 'ü§î –ü—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞, —Å–∫–æ—Ä–µ–µ –≤—Å–µ–≥–æ –≤—ã –æ—à–∏–±–ª–∏—Å—å –≤ –≤–≤–æ–¥–µ –∫–æ–¥–∞.<br>–ß—Ç–æ–±—ã –ø—Ä–∏–≤—è–∑–∞—Ç—å - –Ω–∞–ø–∏—à–∏—Ç–µ –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ /addvk'
    confirmation-not-enough-arguments: '–í—ã –Ω–µ —É–∫–∞–∑–∞–ª–∏ –∫–æ–¥! –í–æ–∑–º–æ–∂–Ω–æ –≤—ã –∑–∞–±—ã–ª–∏ –ø–æ—Å—Ç–∞–≤–∏—Ç—å –ø—Ä–æ–±–µ–ª'
    # –ü–µ—Ä–µ–∫–ª—é—á–µ–Ω–∏–µ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–π –≤—Ö–æ–¥–∞ 
    confirmation-toggle-disabled: '–§—É–Ω–∫—Ü–∏—è –ø–µ—Ä–µ–∫–ª—é—á–µ–Ω–∏—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è –í–ö –æ—Ç–∫–ª—é—á–µ–Ω–∞ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–µ–π.'
    confirmation-toggled: '–í—ã —É—Å–ø–µ—à–Ω–æ –ø–µ—Ä–µ–∫–ª—é—á–∏–ª –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ –≤—Ö–æ–¥–∞ –≤ –í–ö'
    confirmation-no-player: '–í—ã –Ω–µ —É–∫–∞–∑–∞–ª–∏ –∏–≥—Ä–æ–∫–∞ —É –∫–æ—Ç–æ—Ä–æ–≥–æ –Ω—É–∂–Ω–æ –ø–µ—Ä–µ–∫–ª—é—á–∏—Ç—å –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ –≤—Ö–æ–¥–∞'
    # –û–±—â–µ–µ
    not-your-account: '–≠—Ç–æ –Ω–µ —Ç–≤–æ–π –∞–∫–∫–∞—É–Ω—Ç!'
    # –°–ø–∏—Å–æ–∫ –∞–∫–∫–∞—É–Ω—Ç–æ–≤ 
    no-accounts: '–£ —Ç–µ–±—è –Ω–µ—Ç—É –∞–∫–∫–∞—É–Ω—Ç–æ–≤'
    no-page-accounts: '–í –¥–∞–Ω–Ω–æ–π —Å—Ç—Ä–∞–Ω–∏—Ü–µ –æ—Ç—Å—É—Ç—Å–≤—É—é—Ç –∞–∫–∫–∞—É–Ω—Ç—ã!'
    accounts: '–¢–≤–æ–∏ –∞–∫–∫–∞—É–Ω—Ç—ã:'
    # –ù–∞—Å—Ç—Ä–æ–π–∫–∞ –∞–∫–∫–∞—É–Ω—Ç–∞
    account-control: '–ù–∞—Å—Ç—Ä–æ–π–∫–∞ –∞–∫–∫–∞—É–Ω—Ç–∞: %name%'
    # –í–æ—Å—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω–∏–µ –∞–∫–∫–∞—É–Ω—Ç–∞
    restore-not-enough-arguments: '–í—ã –Ω–µ —É–∫–∞–∑–∞–ª–∏ –Ω–∏–∫ –∏–≥—Ä–æ–∫–∞!'
    restored: '–¢–µ–ø–µ—Ä—å –ø–∞—Ä–æ–ª—å –æ—Ç –∞–∫–∫–∞—É–Ω—Ç–∞ %name% - %password%'
    # –ö–∏–∫ –∞–∫–∫–∞—É–Ω—Ç–∞
    kick-not-enough-arguments: '–í—ã –Ω–µ —É–∫–∞–∑–∞–ª–∏ –Ω–∏–∫ –∏–≥—Ä–æ–∫–∞!'
    kick-starting: '‚úÖ –ê–∫–∫–∞—É–Ω—Ç %nick% –±—É–¥–µ—Ç –∫–∏–∫–Ω—É—Ç —Å —Å–µ—Ä–≤–µ—Ä–∞ –≤ —Ç–µ—á–µ–Ω–∏–µ 5 —Å–µ–∫—É–Ω–¥ –µ—Å–ª–∏ –æ–Ω –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ!'
    player-offline: '‚Ñπ –ò–≥—Ä–æ–∫ —Å –Ω–∏–∫–æ–º %nick% –Ω–µ –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ!'
    kicked: '%nick% –±—ã–ª –∫–∏–∫–Ω—É—Ç –∏–∑ —Å–µ—Ä–≤–µ—Ä–∞'
    # –°–º–µ–Ω–∞ –ø–∞—Ä–æ–ª—è
    changepass-not-enough-arguments: '–í—ã –Ω–µ —É–∫–∞–∑–∞–ª–∏ –Ω–∏–∫ –∏ –ø–∞—Ä–æ–ª—å –∏–≥—Ä–æ–∫–∞!'
    changepass-nothing-to-change: '–ù–∏—á–µ–≥–æ –Ω–µ –∏–∑–º–µ–Ω–∏–ª–æ—Å—å!'
    changepass-password-too-short: '–ù–æ–≤—ã–π –ø–∞—Ä–æ–ª—å —Å–ª–∏—à–∫–æ–º –∫–æ—Ä–æ—Ç–∫–∏–π'
    changepass-password-too-long: '–ù–æ–≤—ã–π –ø–∞—Ä–æ–ª—å —Å–ª–∏—à–∫–æ–º –¥–ª–∏–Ω–Ω—ã–π!'
    changepass-success: '–£—Å–ø–µ—à–Ω–æ –∏–∑–º–µ–Ω—ë–Ω –ø–∞—Ä–æ–ª—å –∏–≥—Ä–æ–∫–∞ %name% –Ω–∞ %password%'
    # –ü–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ –≤—Ö–æ–¥–∞ —á–µ—Ä–µ–∑ –í–ö
    enter-no-accounts: '–í–∞–º –Ω–µ –æ—Ç–ø—Ä–∞–≤–ª—è–ª–∏ –ø–∏—Å—å–º–æ –¥–ª—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è –≤—Ö–æ–¥–∞ ü§î'
    enter-message: '‚ö† –ü–æ–ø—ã—Ç–∫–∞ –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏–∏ –Ω–∞ –≤–∞—à –∞–∫–∫–∞—É–Ω—Ç %nick% —Å IP –∞–¥—Ä–µ—Å–∞ %account_ip%. –í–≤–µ–¥–∏—Ç–µ /–ø—Ä–∏–Ω—è—Ç—å –∏–ª–∏ /–æ—Ç–∫–ª–æ–Ω–∏—Ç—å, –ª–∏–±–æ –Ω–∞–∂–º–∏—Ç–µ –Ω–∞ –∫–Ω–æ–ø–∫–∏'
    enter-declined: '–í—ã –æ—Ç–º–µ–Ω–∏–ª–∏ –≤—Ö–æ–¥'
    enter-accepted: '–í—ã —É—Å–ø–µ—à–Ω–æ –≤–æ—à–ª–∏ –≤ –∞–∫–∫–∞—É–Ω—Ç!'
    enter-disabled: '–í—ã —É—Å–ø–µ—à–Ω–æ –≤—ã–∫–ª—é—á–∏–ª–∏ –ø–æ–¥—Ç–≤–µ—Ä–¥–µ–Ω–∏–µ –≤—Ö–æ–¥–∞! –ë—É–¥—å—Ç–µ –æ—Å—Ç–æ—Ä–æ–∂–Ω–µ–µ'
    enter-enabled: '–í—ã —É—Å–ø–µ—à–Ω–æ –≤–∫–ª—é—á–∏–ª–∏ –ø–æ–¥—Ç–≤–µ—Ä–¥–µ–Ω–∏–µ –≤—Ö–æ–¥–∞! –¢–µ–ø–µ—Ä—å –≤—ã –≤ –±–µ–∑–æ–ø–∞—Å–Ω–æ—Å—Ç–∏'
    # –û—Ç–≤—è–∑–∫–∞ –∞–∫–∫–∞—É–Ω—Ç–∞ –í–ö
    unlink-not-enough-arguments: '–í—ã –Ω–µ —É–∫–∞–∑–∞–ª–∏ –Ω–∏–∫ –∏–≥—Ä–æ–∫–∞!'
    unlinked: '–í—ã —É—Å–ø–µ—à–Ω–æ –æ—Ç–≤—è–∑–∞–ª–∏ –∞–∫–∫–∞—É–Ω—Ç %name%'
    # –ê–¥–º–∏–Ω-–ø–∞–Ω–µ–ª—å
    admin-panel: '–ê–¥–º–∏–Ω –ø–∞–Ω–µ–ª—å:'
    admin-panel-no-accounts: '–ù–µ –Ω–∞–π–¥–µ–Ω–æ –∞–∫–∫–∞—É–Ω—Ç–æ–≤!'
    admin-panel-no-linked-accounts: '–ù–µ –Ω–∞–π–¥–µ–Ω–æ –ø—Ä–∏–≤—è–∑–∞–Ω–Ω—ã—Ö –∞–∫–∫–∞—É–Ω—Ç–æ–≤!'
    admin-panel-accounts: '–í—Å–µ –∞–∫–∫–∞—É–Ω—Ç—ã —Å–µ—Ä–≤–µ—Ä–∞:'
    admin-panel-linked-accounts: '–í—Å–µ –ø—Ä–∏–≤—è–∑–∞–Ω–Ω—ã–µ –∞–∫–∫–∞—É–Ω—Ç—ã —Å–µ—Ä–≤–µ—Ä–∞'
    # –ì—É–≥–ª-–ö–æ–¥-–ê—É—Ç–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏—è
    google-disabled: '–ì—É–≥–ª-–ê—É—Ç–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏—è –æ—Ç–∫–ª—é—á–µ–Ω–∞!'
    google-code-not-enough-arguments: '–ù–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –∞—Ä–≥—É–º–µ–Ω—Ç–æ–≤! –ü—Ä–∞–≤–∏–ª—å–Ω—ã–π –≤–≤–æ–¥: /–≥—É–≥–ª-–∫–æ–¥ [–Ω–∏–∫] [–∫–æ–¥]'
    google-code-not-need-enter: '–í–≤–æ–¥–∏—Ç—å –∫–æ–¥ –≥—É–≥–ª –Ω–µ–∑–∞—á–µ–º!'
    google-code-account-not-have-google: '–û—à–∏–±–∫–∞! –£ –∞–∫–∫–∞—É–Ω—Ç–∞ –Ω–µ—Ç—É –≥—É–≥–ª-–∫–ª—é—á–∞'
    google-code-account-not-need-enter: '–í—Ö–æ–¥ —á–µ—Ä–µ–∑ –≥—É–≥–ª –∞—É—Ç–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏—é –Ω–µ —Ç—Ä–µ–±—É–µ—Ç—Å—è!'
    google-code-not-valid: '–í–≤–µ–¥–µ–Ω–Ω—ã–π –∫–æ–¥ –Ω–µ–ø—Ä–∞–≤–∏–ª—å–Ω—ã–π!'
    google-code-valid: '–í–≤–µ–¥–µ–Ω–Ω—ã–π –∫–æ–¥ –ø—Ä–∞–≤–∏–ª—å–Ω—ã–π'
    google-code-need-integer: '–û—à–∏–±–∫–∞! –í—ã –¥–æ–ª–∂–Ω—ã –≤–≤–µ—Å—Ç–∏ 6 –∑–Ω–∞—á–Ω—É—é —Ü–∏—Ñ—Ä—É!'
    # –ì—É–≥–ª-–ì–µ–Ω–µ—Ä–∞—Ü–∏—è
    google-not-enough-arguments: '–ù–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –∞—Ä–≥—É–º–µ–Ω—Ç–æ–≤! –ü—Ä–∞–≤–∏–ª—å–Ω—ã–π –≤–≤–æ–¥: /–≥—É–≥–ª [–Ω–∏–∫]'
    google-generated: '–í—ã —É—Å–ø–µ—à–Ω–æ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–ª–∏ –∫–ª—é—á Google-Authenticator: %google_key%'
    google-regenerated: '–í–Ω–∏–º–∞–Ω–∏–µ! –í—ã –∑–∞–Ω–æ–≥–æ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–ª–∏ –∫–ª—é—á Google Authenticator: %google_key%'
    google-error: '–ü—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞! –°–æ–æ–±—â–∏—Ç–µ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä—É!'
    # –ì—É–≥–ª-–û—Ç–≤—è–∑–∫–∞
    google-unlink-not-enough-arguments: '–ù–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –∞—Ä–≥—É–º–µ–Ω—Ç–æ–≤! –ü—Ä–∞–≤–∏–ª—å–Ω—ã–π –≤–≤–æ–¥: /–≥—É–≥–ª–æ—Ç–≤—è–∑–∞—Ç—å [–Ω–∏–∫]'
    google-unlink-not-have-google: '–û—à–∏–±–∫–∞! –£ –∞–∫–∫–∞—É–Ω—Ç–∞ –Ω–µ—Ç—É –≥—É–≥–ª –∫–ª—é—á–∞'
    google-unlinked: '–ì—É–≥–ª —É—Å–ø–µ—à–Ω–æ —Å–±—Ä–æ—à–µ–Ω!'
    
    not-enough-permission: '–ù–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –ø—Ä–∞–≤ –¥–ª—è –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —ç—Ç–æ–π –∫–æ–º–∞–Ω–¥—ã! –í—ã –¥–æ–ª–∂–Ω—ã –¥–æ–±–∞–≤–∏—Ç—å —Å–µ–±—è –≤ —Å–ø–∏—Å–æ–∫ –∞–¥–º–∏–Ω–æ–≤!'
    
    unresolved-argument: '–í—ã –Ω–µ —É–∫–∞–∑–∞–ª–∏ –∞—Ä–≥—É–º–µ–Ω—Ç: %argument_name%'
    unresolved-number: '–û–∂–∏–¥–∞–ª–æ—Å—å —á–∏—Å–ª–æ, –Ω–æ –≤—ã —É–∫–∞–∑–∞–ª–∏ %input%'
    command-invocation: '–ü—Ä–∏ –≤–≤–æ–¥–µ –∫–æ–º–∞–Ω–¥—ã –ø—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞, —Å–æ–æ–±—â–∏—Ç–µ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏–∏'